src/objects/Chatter_Bot_Group_Member__c.object
<CustomObject>
    <description>A record is created via trigger any time a user is added as a member to the Chatter Group that the parent Chatter Bot Group is monitoring. This allows you to setup Process Builder to be fired when these records are created so that you can take action on member assignments. This is a workaround until if or when Salesforce supports CollaborationGroupMember object in Process Builder.</description>
    <fields>
        <fullName>Chatter_Group_Member_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Chatter Group Member ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Is_Member__c</fullName>
        <defaultValue>true</defaultValue>
        <description>So that you can be notified when users are removed from groups, the trigger will on delete of CollaborationGroupMember records uncheck this field then delete this record. You can use Workflow or Process Builder to monitor for this field changing to know if user has been removed from the group.</description>
        <inlineHelpText>So that you can be notified when users are removed from groups, the trigger will on delete of CollaborationGroupMember records uncheck this field then delete this record. You can use Workflow or Process Builder to monitor for this field changing.</inlineHelpText>
        <label>Is Member?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Chatter_Bot_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Chatter Bot Group Member</label>
    <nameField>
        <displayFormat>CBGM-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chatter Bot Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Chatter_Bot_Groups_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Preferences for Chatter Bot Groups</description>
    <fields>
        <fullName>Auto_Create_Public_Chatter_Groups__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When checked then apex trigger will upsert a Chatter Bot Group record any time a public CollaborationGroup (Chatter Group) is created or updated. When unchecked, an administrator must manually create a Chatter Bot Group record to begin monitoring.</description>
        <inlineHelpText>When checked then apex trigger will upsert a Chatter Bot Group record any time a public CollaborationGroup (Chatter Group) is created or updated. When unchecked, an administrator must manually create a Chatter Bot Group record to begin monitoring.</inlineHelpText>
        <label>Auto Create Public Chatter Groups?</label>
        <type>Checkbox</type>
    </fields>
    <label>Chatter Bot Groups Setting</label>
</CustomObject>

src/classes/ChatterBotGroupMemberTriggerHandlerTest.cls
/**
 * Developed by Doug Ayers
 * douglascayers.com
 */
@isTest
private class ChatterBotGroupMemberTriggerHandlerTest {

    @isTest
    static void test_add_group_member() {

        Profile p = [ SELECT id FROM Profile WHERE name = 'Standard User' ];

        User user1;

        // https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_testing_tools_runas.htm
        System.runAs( new User( id = UserInfo.getUserId() ) ) {

            user1 = newUser( p.id, 'Alpha', 'User 1', 'user_1@example.com' );

            insert new List<User>{ user1 };

        }

        Chatter_Bot_Groups_Setting__c settings = Chatter_Bot_Groups_Setting__c.getInstance();
        settings.auto_create_public_chatter_groups__c = true;
        upsert settings;

        CollaborationGroup grp = new CollaborationGroup(
            name = 'Test Group',
            collaborationType = 'Public'
        );

        insert grp;

        Test.startTest();

        CollaborationGroupMember groupMember = new CollaborationGroupMember(
            collaborationGroupId = grp.id,
            memberId = user1.id,
            collaborationRole = 'Standard'
        );

        insert groupMember;

        Test.stopTest();

        Chatter_Bot_Group_Member__c chatterBotGroupMember = [ SELECT id, chatter_group_member_id__c, member__c, role__c, is_member__c FROM Chatter_Bot_Group_Member__c WHERE member__c = :user1.id ];

        System.assertEquals( groupMember.id, chatterBotGroupMember.chatter_group_member_id__c );
        System.assertEquals( groupMember.collaborationRole, chatterBotGroupMember.role__c );
        System.assertEquals( true, chatterBotGroupMember.is_member__c );

    }

    @isTest
    static void test_remove_group_member() {

        Profile p = [ SELECT id FROM Profile WHERE name = 'Standard User' ];

        User user1;

        // https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_testing_tools_runas.htm
        System.runAs( new User( id = UserInfo.getUserId() ) ) {

            user1 = newUser( p.id, 'Alpha', 'User 1', 'user_1@example.com' );

            insert new List<User>{ user1 };

        }

        Chatter_Bot_Groups_Setting__c settings = Chatter_Bot_Groups_Setting__c.getInstance();
        settings.auto_create_public_chatter_groups__c = true;
        upsert settings;

        CollaborationGroup grp = new CollaborationGroup(
            name = 'Test Group',
            collaborationType = 'Public'
        );

        insert grp;

        CollaborationGroupMember groupMember = new CollaborationGroupMember(
            collaborationGroupId = grp.id,
            memberId = user1.id,
            collaborationRole = 'Standard'
        );

        insert groupMember;

        System.assertEquals( 1, [ SELECT count() FROM Chatter_Bot_Group_Member__c WHERE chatter_group_member_id__c = :groupMember.id ] );

        Test.startTest();

        delete groupMember;

        Test.stopTest();

        System.assertEquals( 0, [ SELECT count() FROM Chatter_Bot_Group_Member__c WHERE chatter_group_member_id__c = :groupMember.id ] );

    }

    private static User newUser( ID profileId, String firstName, String lastName, String email ) {
        Integer rand = Math.round( Math.random() * 1000 );
        return new User(
            isActive = true,
            profileId = profileId,
            alias = firstName.substring(0,1) + lastName.substring(1,5),
            firstName = firstName,
            lastName = lastName,
            email = email,
            username = rand + email,
            emailEncodingKey = 'UTF-8',
            languageLocaleKey = 'en_US',
            localeSidKey = 'en_US',
            timeZoneSidKey = 'America/Chicago'
        );
    }

}