src/objects/Chatter_Bot_Group__c.object
<CustomObject>
    <description>Specify Chatter Groups that you want to be notified when they are updated or when someone joins the group.so that you can take actions. A common use case is to send a welcome email or Chatter post to new members of a group. This is a workaround until if or when Salesforce supports CollaborationGroup object in Process Builder.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Controls whether the Chatter Group and Chatter Group Member triggers create/update/delete Chatter Bot Group Member child records when users join or leave a group.</description>
        <inlineHelpText>Controls whether the Chatter Group and Chatter Group Member triggers create/update/delete Chatter Bot Group Member child records when users join or leave a group.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Chatter_Group_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>ID of the Chatter Group to monitor.</description>
        <externalId>true</externalId>
        <inlineHelpText>ID of the Chatter Group to monitor.</inlineHelpText>
        <label>Chatter Group ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Collaboration_Type__c</fullName>
        <label>Collaboration Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Chatter Bot Group</label>
    <nameField>
        <displayFormat>CBG-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chatter Bot Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Chatter_Bot_Groups_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Preferences for Chatter Bot Groups</description>
    <fields>
        <fullName>Auto_Create_Public_Chatter_Groups__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When checked then apex trigger will upsert a Chatter Bot Group record any time a public CollaborationGroup (Chatter Group) is created or updated. When unchecked, an administrator must manually create a Chatter Bot Group record to begin monitoring.</description>
        <inlineHelpText>When checked then apex trigger will upsert a Chatter Bot Group record any time a public CollaborationGroup (Chatter Group) is created or updated. When unchecked, an administrator must manually create a Chatter Bot Group record to begin monitoring.</inlineHelpText>
        <label>Auto Create Public Chatter Groups?</label>
        <type>Checkbox</type>
    </fields>
    <label>Chatter Bot Groups Setting</label>
</CustomObject>

src/classes/ChatterBotGroupTriggerHandlerTest.cls
/**
 * Developed by Doug Ayers
 * douglascayers.com
 */
@isTest
private class ChatterBotGroupTriggerHandlerTest {

    @isTest
    static void test_auto_create_chatter_bot_group() {

        Chatter_Bot_Groups_Setting__c settings = Chatter_Bot_Groups_Setting__c.getInstance();
        settings.auto_create_public_chatter_groups__c = true;
        upsert settings;

        Test.startTest();

        CollaborationGroup grp = new CollaborationGroup(
            name = 'Test Group',
            collaborationType = 'Public'
        );

        insert grp;

        Test.stopTest();

        System.assertEquals( 1, [ SELECT count() FROM Chatter_Bot_Group__c WHERE chatter_group_id__c = :grp.id ] );

    }

    @isTest
    static void test_no_auto_create_chatter_bot_group() {

        Chatter_Bot_Groups_Setting__c settings = Chatter_Bot_Groups_Setting__c.getInstance();
        settings.auto_create_public_chatter_groups__c = false;
        upsert settings;

        Test.startTest();

        CollaborationGroup grp = new CollaborationGroup(
            name = 'Test Group',
            collaborationType = 'Public'
        );

        insert grp;

        Test.stopTest();

        System.assertEquals( 0, [ SELECT count() FROM Chatter_Bot_Group__c WHERE chatter_group_id__c = :grp.id ] );

    }

    @isTest
    static void test_update_group() {

        CollaborationGroup grp = new CollaborationGroup(
            name = 'Test Group',
            collaborationType = 'Public'
        );

        insert grp;

        Chatter_Bot_Group__c chatterBotGroup = new Chatter_Bot_Group__c(
            chatter_group_id__c = grp.id,
            active__c = true
        );

        insert chatterBotGroup;

        Test.startTest();

        update grp;

        Test.stopTest();

        chatterBotGroup = [ SELECT id, chatter_group_id__c, group_name__c, collaboration_type__c FROM Chatter_Bot_Group__c WHERE id = :chatterBotGroup.id ];

        System.assertEquals( grp.id, chatterBotGroup.chatter_group_id__c );
        System.assertEquals( grp.name, chatterBotGroup.group_name__c );
        System.assertEquals( grp.collaborationType, chatterBotGroup.collaboration_type__c );

    }

    @isTest
    static void test_delete_group() {

        Chatter_Bot_Groups_Setting__c settings = Chatter_Bot_Groups_Setting__c.getInstance();
        settings.auto_create_public_chatter_groups__c = true;
        upsert settings;

        CollaborationGroup grp = new CollaborationGroup(
            name = 'Test Group',
            collaborationType = 'Public'
        );

        insert grp;

        System.assertEquals( 1, [ SELECT count() FROM Chatter_Bot_Group__c WHERE chatter_group_id__c = :grp.id ] );

        Test.startTest();

        delete grp;

        Test.stopTest();

        System.assertEquals( 0, [ SELECT count() FROM Chatter_Bot_Group__c WHERE chatter_group_id__c = :grp.id ] );

    }

}