src/objects/Chatter_Bot_Group__c.object
<CustomObject>
    <description>Specify Chatter Groups that you want to be notified when they are updated or when someone joins the group.so that you can take actions. A common use case is to send a welcome email or Chatter post to new members of a group. This is a workaround until if or when Salesforce supports CollaborationGroup object in Process Builder.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Controls whether the Chatter Group and Chatter Group Member triggers create/update/delete Chatter Bot Group Member child records when users join or leave a group.</description>
        <inlineHelpText>Controls whether the Chatter Group and Chatter Group Member triggers create/update/delete Chatter Bot Group Member child records when users join or leave a group.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Chatter_Group_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>ID of the Chatter Group to monitor.</description>
        <externalId>true</externalId>
        <inlineHelpText>ID of the Chatter Group to monitor.</inlineHelpText>
        <label>Chatter Group ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Chatter Bot Group</label>
    <nameField>
        <displayFormat>CBG-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chatter Bot Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Chatter_Bot_Group_Member__c.object
<CustomObject>
    <description>A record is created via trigger any time a user is added as a member to the Chatter Group that the parent Chatter Bot Group is monitoring. This allows you to setup Process Builder to be fired when these records are created so that you can take action on member assignments. This is a workaround until if or when Salesforce supports CollaborationGroupMember object in Process Builder.</description>
    <fields>
        <fullName>Chatter_Bot_Group__c</fullName>
        <label>Chatter Bot Group</label>
        <referenceTo>Chatter_Bot_Group__c</referenceTo>
        <relationshipLabel>Chatter Bot Group Members</relationshipLabel>
        <relationshipName>Chatter_Bot_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Chatter_Group_ID__c</fullName>
        <description>The Chatter Group ID this user is a member of.</description>
        <formula>Chatter_Bot_Group__r.Chatter_Group_ID__c</formula>
        <inlineHelpText>The Chatter Group ID this user is a member of.</inlineHelpText>
        <label>Chatter Group ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Chatter_Group_Member_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Chatter Group Member ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Is_Member__c</fullName>
        <defaultValue>true</defaultValue>
        <description>So that you can be notified when users are removed from groups, the trigger will on delete of CollaborationGroupMember records uncheck this field then delete this record. You can use Workflow or Process Builder to monitor for this field changing to know if user has been removed from the group.</description>
        <inlineHelpText>So that you can be notified when users are removed from groups, the trigger will on delete of CollaborationGroupMember records uncheck this field then delete this record. You can use Workflow or Process Builder to monitor for this field changing.</inlineHelpText>
        <label>Is Member?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Chatter_Bot_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Chatter Bot Group Member</label>
    <nameField>
        <displayFormat>CBGM-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chatter Bot Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ChatterBotGroupMemberTriggerHandler.cls
/**
 * Developed by Doug Ayers
 * douglascayers.com
 *
 * Note, 'without sharing' is used in this class.
 * Most users will not have sharing access to the Chatter_Bot_Group_Member__c object
 * but we want to ensure this trigger handler can update those records anytime
 * a group member is added or removed.
 * https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_keywords_sharing.htm
 */
public without sharing class ChatterBotGroupMemberTriggerHandler {

    public void upsertChatterBotGroupMembers( List<CollaborationGroupMember> groupMembers, Boolean isMember ) {

        // When filtering on lookup fields, Salesforce has special
        // handling to treat 15 and 18 character IDs the same.
        // Since our query is on a text field and not an ID lookup field
        // then we have to handle both 15 and 18 character IDs as unique
        // values in our filter criteria.
        Set<String> groupIds = new Set<String>();
        for ( CollaborationGroupMember member : groupMembers ) {
            groupIds.add( member.collaborationGroupId );
            groupIds.add( String.valueOf( member.collaborationGroupId ).left( 15 ) );
        }

        // group id => chatter bot group
        Map<ID, Chatter_Bot_Group__c> groupIdToChatterBotGroupMap = new Map<ID, Chatter_Bot_Group__c>();
        for ( Chatter_Bot_Group__c chatterBotGroup : [
            SELECT
                id, chatter_group_id__c, active__c
            FROM
                Chatter_Bot_Group__c
            WHERE
                chatter_group_id__c IN :groupIds
        ]) {
            groupIdToChatterBotGroupMap.put( chatterBotGroup.chatter_group_id__c, chatterBotGroup );
        }

        List<Chatter_Bot_Group_Member__c> chatterBotGroupMembersToUpsert = new List<Chatter_Bot_Group_Member__c>();

        for ( CollaborationGroupMember member : groupMembers ) {

            Chatter_Bot_Group__c chatterBotGroup = groupIdToChatterBotGroupMap.get( member.collaborationGroupId );

            if ( chatterBotGroup != null && chatterBotGroup.active__c ) {

                chatterBotGroupMembersToUpsert.add( new Chatter_Bot_Group_Member__c(
                    chatter_bot_group__c = chatterBotGroup.id,
                    chatter_group_member_id__c = member.id,
                    member__c = member.memberId,
                    role__c = member.collaborationRole,
                    is_member__c = isMember
                ));

            }

        }

        if ( chatterBotGroupMembersToUpsert.size() > 0 ) {
            Database.upsert( chatterBotGroupMembersToUpsert, Chatter_Bot_Group_Member__c.Chatter_Group_Member_ID__c );
        }

    }

    public void deleteChatterBotGroupMembers( List<CollaborationGroupMember> groupMembers ) {

        // When filtering on lookup fields, Salesforce has special
        // handling to treat 15 and 18 character IDs the same.
        // Since our query is on a text field and not an ID lookup field
        // then we have to handle both 15 and 18 character IDs as unique
        // values in our filter criteria.
        Set<String> groupMemberIds = new Set<String>();
        for ( CollaborationGroupMember member : groupMembers ) {
            groupMemberIds.add( member.id );
            groupMemberIds.add( String.valueOf( member.id ).left( 15 ) );
        }

        List<Chatter_Bot_Group_Member__c> chatterBotGroupMembers = new List<Chatter_Bot_Group_Member__c>([
            SELECT
                id, is_member__c
            FROM
                Chatter_Bot_Group_Member__c
            WHERE
                chatter_group_member_id__c IN :groupMemberIds
            ORDER BY
                chatter_bot_group__c
        ]);

        // delete records since users no longer group members
        delete chatterBotGroupMembers;

    }

}