src/objects/Chatter_Bot_Group__c.object
<CustomObject>
    <description>Specify Chatter Groups that you want to be notified when they are updated or when someone joins the group.so that you can take actions. A common use case is to send a welcome email or Chatter post to new members of a group. This is a workaround until if or when Salesforce supports CollaborationGroup object in Process Builder.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Controls whether the Chatter Group and Chatter Group Member triggers create/update/delete Chatter Bot Group Member child records when users join or leave a group.</description>
        <inlineHelpText>Controls whether the Chatter Group and Chatter Group Member triggers create/update/delete Chatter Bot Group Member child records when users join or leave a group.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Banner_Photo_URL__c</fullName>
        <label>Banner Photo URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Can_Have_Guests__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Can Have Guests?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Chatter_Group_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>ID of the Chatter Group to monitor.</description>
        <externalId>true</externalId>
        <inlineHelpText>ID of the Chatter Group to monitor.</inlineHelpText>
        <label>Chatter Group ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Collaboration_Type__c</fullName>
        <label>Collaboration Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Photo_URL__c</fullName>
        <label>Full Photo URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Group_Description__c</fullName>
        <label>Group Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Group_Email__c</fullName>
        <description>The email address for posting Chatter messages to the group.</description>
        <inlineHelpText>The email address for posting Chatter messages to the group.</inlineHelpText>
        <label>Group Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Chatter_Bot_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Information_Body__c</fullName>
        <label>Information Body</label>
        <length>4000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Information_Title__c</fullName>
        <label>Information Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Archived__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Archived?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Broadcast__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Broadcast?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Medium_Photo_URL__c</fullName>
        <label>Medium Photo URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Member_Count__c</fullName>
        <label>Member Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Small_Photo_URL__c</fullName>
        <label>Small Photo URL</label>
        <type>Url</type>
    </fields>
    <label>Chatter Bot Group</label>
    <nameField>
        <displayFormat>CBG-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chatter Bot Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Chatter_Bot_Groups_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Preferences for Chatter Bot Groups</description>
    <fields>
        <fullName>Auto_Create_Private_Chatter_Groups__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When checked then apex trigger will upsert a Chatter Bot Group record any time a private CollaborationGroup (Chatter Group) is created or updated. When unchecked, an administrator must manually create a Chatter Bot Group record to begin monitoring.</description>
        <inlineHelpText>When checked then apex trigger will upsert a Chatter Bot Group record any time a private CollaborationGroup (Chatter Group) is created or updated. When unchecked, an administrator must manually create a Chatter Bot Group record to begin monitoring.</inlineHelpText>
        <label>Auto Create Private Chatter Groups?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Create_Public_Chatter_Groups__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When checked then apex trigger will upsert a Chatter Bot Group record any time a public CollaborationGroup (Chatter Group) is created or updated. When unchecked, an administrator must manually create a Chatter Bot Group record to begin monitoring.</description>
        <inlineHelpText>When checked then apex trigger will upsert a Chatter Bot Group record any time a public CollaborationGroup (Chatter Group) is created or updated. When unchecked, an administrator must manually create a Chatter Bot Group record to begin monitoring.</inlineHelpText>
        <label>Auto Create Public Chatter Groups?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Create_Unlisted_Chatter_Groups__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked then apex trigger will upsert a Chatter Bot Group record any time an unlisted CollaborationGroup (Chatter Group) is created or updated. When unchecked, an administrator must manually create a Chatter Bot Group record to begin monitoring.</description>
        <inlineHelpText>When checked then apex trigger will upsert a Chatter Bot Group record any time an unlisted CollaborationGroup (Chatter Group) is created or updated. When unchecked, an administrator must manually create a Chatter Bot Group record to begin monitoring.</inlineHelpText>
        <label>Auto Create Unlisted Chatter Groups?</label>
        <type>Checkbox</type>
    </fields>
    <label>Chatter Bot Groups Setting</label>
</CustomObject>

src/classes/ChatterBotGroupTriggerHandler.cls
/**
 * Developed by Doug Ayers
 * douglascayers.com
 *
 * Note, 'without sharing' is used in this class.
 * Most users will not have sharing access to the Chatter_Bot_Group__c object
 * but we want to ensure this trigger handler can update those records anytime
 * a group is created or updated.
 * https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_keywords_sharing.htm
 */
public without sharing class ChatterBotGroupTriggerHandler {

    public void upsertChatterBotGroups( List<CollaborationGroup> groups ) {

        // we must re-query the groups to get their photo urls
        // unfortunately, when users upload new photos to groups in UI the trigger isn't fired
        groups = new List<CollaborationGroup>([
            SELECT
                id, name, description, ownerId, collaborationType, groupEmail,
                smallPhotoURL, mediumPhotoURL, fullPhotoURL, bannerPhotoURL,
                memberCount, informationTitle, informationBody, canHaveGuests,
                isArchived, isBroadcast
            FROM
                CollaborationGroup
            WHERE
                id IN :groups
        ]);

        // do any chatter bot groups exist for these group ids?
        // if yes then we should update those records, else ignore
        // unless custom setting says to auto create records anyways

        // When filtering on lookup fields, Salesforce has special
        // handling to treat 15 and 18 character IDs the same.
        // Since our query is on a text field and not an ID lookup field
        // then we have to handle both 15 and 18 character IDs as unique
        // values in our filter criteria.
        Set<String> groupIds = new Set<String>();
        for ( CollaborationGroup grp : groups ) {
            groupIds.add( grp.id );
            groupIds.add( String.valueOf( grp.id ).left( 15 ) );
        }

        // group id => chatter bot group
        Map<ID, Chatter_Bot_Group__c> groupIdToChatterBotGroupMap = new Map<ID, Chatter_Bot_Group__c>();
        for ( Chatter_Bot_Group__c chatterBotGroup : [
            SELECT
                id, chatter_group_id__c, active__c
            FROM
                Chatter_Bot_Group__c
            WHERE
                chatter_group_id__c IN :groupIds
        ]) {
            groupIdToChatterBotGroupMap.put( chatterBotGroup.chatter_group_id__c, chatterBotGroup );
        }

        Chatter_Bot_Groups_Setting__c settings = Chatter_Bot_Groups_Setting__c.getInstance();
        Boolean autoCreatePublicGroups = ( settings != null && settings.auto_create_public_chatter_groups__c );
        Boolean autoCreatePrivateGroups = ( settings != null && settings.auto_create_private_chatter_groups__c );
        Boolean autoCreateUnlistedGroups = ( settings != null && settings.auto_create_unlisted_chatter_groups__c );

        List<Chatter_Bot_Group__c> chatterBotGroupsToUpsert = new List<Chatter_Bot_Group__c>();
        List<Chatter_Bot_Group__c> chatterBotGroupsToUpdate = new List<Chatter_Bot_Group__c>();

        for ( CollaborationGroup grp : groups ) {

            System.debug( grp );

            Chatter_Bot_Group__c chatterBotGroup = groupIdToChatterBotGroupMap.get( grp.id );

            if ( chatterBotGroup == null ) {

                System.debug( 'No Chatter Bot Group record matches collaboration group id: ' + grp.id + ', collaborationGroupType: ' + grp.collaborationType );
                System.debug( 'Should auto create Chatter Bot Group? public: ' + autoCreatePublicGroups + ', private: ' + autoCreatePrivateGroups + ', unlisted: ' + autoCreateUnlistedGroups + '. This option is controlled by Chatter_Bot_Groups_Setting__c custom setting.' );

                Boolean shouldCreate = ( 'Public' == grp.collaborationType && autoCreatePublicGroups ) ||
                                       ( 'Private' == grp.collaborationType && autoCreatePrivateGroups ) ||
                                       ( 'Unlisted' == grp.collaborationType && autoCreateUnlistedGroups );

                if ( shouldCreate ) {
                    chatterBotGroup = new Chatter_Bot_Group__c(
                        active__c = true
                    );
                }

            }

            if ( chatterBotGroup != null && chatterBotGroup.active__c ) {

                chatterBotGroup.chatter_group_id__c = grp.id;
                chatterBotGroup.group_name__c = grp.name;
                chatterBotGroup.group_owner__c = grp.ownerId;
                chatterBotGroup.group_description__c = grp.description;
                chatterBotGroup.group_email__c = grp.groupEmail;
                chatterBotGroup.member_count__c = grp.memberCount;
                chatterBotGroup.can_have_guests__c = grp.canHaveGuests;
                chatterBotGroup.collaboration_type__c = grp.collaborationType;
                chatterBotGroup.small_photo_url__c = grp.smallPhotoURL;
                chatterBotGroup.medium_photo_url__c = grp.mediumPhotoURL;
                chatterBotGroup.full_photo_url__c = grp.fullPhotoURL;
                chatterBotGroup.banner_photo_url__c = grp.bannerPhotoURL;
                chatterBotGroup.information_title__c = grp.informationTitle;
                chatterBotGroup.information_body__c = grp.informationBody;
                chatterBotGroup.is_archived__c = grp.isArchived;
                chatterBotGroup.is_broadcast__c = grp.isBroadcast;

                if ( String.isNotBlank( chatterBotGroup.id ) ) {
                    chatterBotGroupsToUpdate.add( chatterBotGroup );
                } else {
                    chatterBotGroupsToUpsert.add( chatterBotGroup );
                }

            }

        }

        if ( chatterBotGroupsToUpsert.size() > 0 ) {
            Database.upsert( chatterBotGroupsToUpsert, Chatter_Bot_Group__c.Chatter_Group_ID__c );
        }

        if ( chatterBotGroupsToUpdate.size() > 0 ) {
            Database.update( chatterBotGroupsToUpdate );
        }

    }

    public void deleteChatterBotGroups( List<CollaborationGroup> groups ) {

        // When filtering on lookup fields, Salesforce has special
        // handling to treat 15 and 18 character IDs the same.
        // Since our query is on a text field and not an ID lookup field
        // then we have to handle both 15 and 18 character IDs as unique
        // values in our filter criteria.
        Set<String> groupIds = new Set<String>();
        for ( CollaborationGroup grp : groups ) {
            groupIds.add( grp.id );
            groupIds.add( String.valueOf( grp.id ).left( 15 ) );
        }

        delete [ SELECT id FROM Chatter_Bot_Group__c WHERE chatter_group_id__c IN :groupIds ];

    }

}